# Generated by Django 5.2.4 on 2025-07-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='No description provided', max_length=1000),
        ),
    ]
